# Generated by Django 2.1.4 on 2019-01-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_debatecomment'),
        ('pages', '0002_auto_20190115_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='threads',
        ),
        migrations.AddField(
            model_name='profile',
            name='threads',
            field=models.ManyToManyField(to='messaging.Thread'),
        ),
    ]
