# Generated by Django 2.1.4 on 2019-01-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190115_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
