# Generated by Django 2.1.4 on 2019-01-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190117_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
