# Generated by Django 2.1.4 on 2019-01-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190117_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('', '--'), ('LFD', 'Looking for a debate'), ('FYC', 'For your consideration'), ('SI', 'Seeking information'), ('ND', 'New Debate')], max_length=1),
        ),
    ]
