# Generated by Django 2.1.4 on 2019-01-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_debatecomment'),
        ('pages', '0012_auto_20190118_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='messaging.Thread'),
        ),
    ]
