# Generated by Django 2.1.4 on 2019-01-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_post_post_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_thread',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Thread'),
        ),
    ]
