# Generated by Django 2.1.4 on 2019-05-24 02:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0016_auto_20190523_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2019, 5, 24, 2, 49, 58, 314297, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parentChild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ChildPost')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('', '--'), ('Looking for a debate', 'Looking for a debate'), ('For your consideration', 'For your consideration'), ('Seeking information', 'Seeking information'), ('New Debate', 'New Debate')], max_length=1),
        ),
        migrations.AddField(
            model_name='childpost',
            name='parentPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Post'),
        ),
    ]
