# Generated by Django 2.1.4 on 2019-01-11 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20190108_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.Thread'),
        ),
    ]
