# Generated by Django 2.1.4 on 2019-01-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20190111_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
