# Generated by Django 2.1.4 on 2019-01-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_debatecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
